name: DMentions
version: '1.0-BETA5'
main: org.nandayo.Main
api-version: '1.20'
authors: [ yoshii01 ]
softdepend:
  - LuckPerms
commands:
  dmentions:
    aliases: dms
    usage: /dms
permissions:
  dmentions.admin:
    default: op
    children:
      dmentions.reload: true
  dmentions.reload:
    default: op