name: DMentions
version: '1.0'
main: org.nandayo.Main
api-version: '1.20'
authors: [ yoshii01 ]
softdepend:
  - LuckPerms
commands:
  dmentions:
    aliases: dms
    usage: /dms
permissions:
  dmentions.admin:
    default: op
    children:
      dmentions.reload: true
      dmentions.help: true
      dmentions.toggle: true
  dmentions.reload:
    default: op
  dmentions.help:
    default: op
  dmentions.toggle:
    default: op