name: OyuncuEtiket
version: '1.0-BETA'
main: org.nandayo.Main
api-version: '1.20'
authors: [ yoshii01 ]
commands:
  oyuncuetiket:
    aliases: oet
    usage: /oet
permissions:
  oyuncuetiket.admin:
    default: op
    children:
      oyuncuetiket.reload: true
  oyuncuetiket.reload:
    default: op