name: DMentions
version: '1.0-BETA4'
main: org.nandayo.Main
api-version: '1.20'
authors: [ yoshii01 ]
commands:
  dmentions:
    aliases: dms
    usage: /dms
permissions:
  dmentions.admin:
    default: op
    children:
      dmentions.reload: true
      dmentions.mention.player: true
      dmentions.mention.everyone: true
  dmentions.reload:
    default: op
  dmentions.mention.player:
    default: op
  dmentions.mention.everyone:
    default: op